### ISSUE TITLE
Settings from pyproject.yml not used

### ISSUE THREAD

**Issue by whyscream** [thep0y/python-black#23]
I have `python-black 1.2.0` installed through package control. My `pyproject.yml` looks like this:

```yaml
[tool.black]
line-length = 119
target-version = ['py310']
```

Both `format on save` and the context menu `Black -> Format file` format the file, but don't respect my custom line length.

**Comment by nk9** [comment]
I'm having the same problem. The line-length setting is being ignored now. I've had to turn off the plugin for the time being. Here's the relevant portion of `./pyproj.toml`:

```toml
[tool.black]
extend-exclude = "^/migrations/"
line-length = 120
```
